blank_issues_enabled: false
contact_links:
  - name: Relybytes Support
    url: https://discord.com/channels/961242813524242554/1126083972414308412
    about: Fro support use the discord channerl of relybytes or the specific team channel on discord
